# Generated by Django 4.2.3 on 2023-07-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("total_quantity", models.IntegerField()),
                ("lot_size", models.IntegerField()),
                ("interval", models.IntegerField()),
                ("premium", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=10)),
                ("trade", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
